apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-cluster
  spec:
    acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      email: example@example.com
      privateKeySecretRef:
        name: letsencrypt-prod
      solvers:
        - http01:
            ingress:
              class: nginx