apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nextcloud-ingress
    namespace: ingress
    # annotations:
    #     kubernetes.io/ingress.class: nginx-class
    #     cert-manager.io/cluster-issuer: letsencrypt-cluster
    #     cert-manager.io/acme-challenge-type: http01
spec:
    ingressClassName: nginx
    rules:
        - host: nextcloud.local
          http: 
              paths: 
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: nextcloud
                        port:
                          number: 80
    tls:
      - hosts: 
          - nextcloud.local
          secretName: letsencrypt