# apiVersion: v1
# kind: ConfigMap
# data:
#   proxy-connect-timeout: "10s"
#   proxy-read-timeout: "10s"
#   client-max-body-size: "10G"
# metadata:
#   name: ingress-nginx-conf
#   namespace: ingress-nginx

apiVersion: v1
data:
  allow-snippet-annotations: "true"
  client-max-body-size: "10G"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.7.1
  name: ingress-nginx-controller
  namespace: ingress-nginx
---