kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jellyfin-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10000G
spec:
  ingressClassName: nginx
  rules:
  - host: jellyfin.atweek.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: 8096
  tls:
  - hosts:
     - jellyfin.atweek.work
    secretName: ssl-cert-production
