    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nexus
    spec:
      replicas: 1
      selector:
        matchLabels:
            app: nexus
      template:
        metadata:
          labels:
            app: nexus
        spec:
          containers:
            - name: nexus
              image: mirror.gcr.io/klo2k/nexus3
              resources:
                limits:
                  memory: "4Gi"
                  cpu: "1000m"
                requests:
                  memory: "2Gi"
                  cpu: "500m"
              ports:
                - containerPort: 8081
              volumeMounts:
                - name: nexus-pvc
                  mountPath: nexus-data
          volumes:
          - name: nexus-pvc
            persistentVolumeClaim:
              claimName: nexus-pvc
