apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: letsencrypt-cluster
spec:
    acme:
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      email: example@example.com
      privateKeySecretRef:
          name: letsencrypt
      solvers:
        - http01:
            ingress:
              class: nginx