# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisione
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#     name: maria-pv
# spec:
#     capacity:
#         storage: 10Gi
#     volumeMode: Filesystem
#     accessModes:
#         - ReadWriteOnce 
#     persistentVolumeReclaimPolicy: Delete #Retain в будущем заменеить
#     storageClassName: "local-storage"
#     local:
#         path: /mnt/flesh/mariadb #TODO Надо потом добавть
                    
# ...
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mariadb-pv
    labels:
        type: local
spec:
    storageClassName: mariadb-disk
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/flesh/mariadb
    persistentVolumeReclaimPolicy: Delete #Retain в будущем заменеить  
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nextcloud-pv
    labels:
        type: local
spec:
    storageClassName: nextcloud-disk
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/flesh/nextcloud
    persistentVolumeReclaimPolicy: Delete #Retain в будущем заменеить                   
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: transmission-pv
    labels:
        type: local
spec:
    storageClassName: transmission-disk
    capacity:
        storage: 5Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/flesh/transmission
    persistentVolumeReclaimPolicy: Delete #Retain в будущем заменеить                   
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 9Gi
    storageClassName: mariadb-disk
    volumeName: mariadb-pv
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nextcloud-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 9Gi
    storageClassName: nextcloud-disk
    volumeName: nextcloud-pv
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: transmission-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: transmission-disk
    volumeName: transmission-pv
