apiVersion: v1
kind: PersistentVolume
metadata:
    name: mariadb-pv
    labels:
        type: local
spec:
    storageClassName: mariadb-disk
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/disk/mariadb
    persistentVolumeReclaimPolicy: Retain #Retain в будущем заменеить  
---
 apiVersion: v1
 kind: PersistentVolume
 metadata:
     name: nextcloud-pv
     labels:
         type: local
 spec:
     storageClassName: nextcloud-disk
     capacity:
         storage: 10Gi
     volumeMode: Filesystem
     accessModes:
         - ReadWriteOnce
     hostPath:
         path: /mnt/disk/nextcloud
     persistentVolumeReclaimPolicy: Retain #Retain в будущем заменеить                   
---
 apiVersion: v1
 kind: PersistentVolume
 metadata:
     name: transmission-pv
     labels:
         type: local
 spec:
     storageClassName: transmission-disk
     capacity:
         storage: 5Gi
     volumeMode: Filesystem
     accessModes:
         - ReadWriteOnce
     hostPath:
         path: /mnt/disk/transmission
     persistentVolumeReclaimPolicy: Retain #Retain в будущем заменеить                   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 9Gi
    storageClassName: mariadb-disk
    volumeName: mariadb-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nextcloud-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 9Gi
    storageClassName: nextcloud-disk
    volumeName: nextcloud-pv
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: transmission-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: transmission-disk
    volumeName: transmission-pv