# ---
#PersistentVolume hard drive
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#     name: disk
# spec:
#     capacity:
#         storage: 28Gi
#     volumeMode: Filesystem
#     accessModes:
#         - ReadWriteOnce 
#     persistentVolumeReclaimPolicy: Delete
#     storageClassName: disk #TODO Разделить и сделать отдельно для каждой PVC и как деплоймент создал pvc в определенном месте на хосте
#     local:
#         path: /mnt/flesh/ #TODO Надо потом добавть
    # nodeAffinity:
    #     required:
    #         nodeSelectorTerms:
    #             - matchExpressions:
    #                   - key: kubernetes.io/hostname
    #                     operator: In
    #                     values:
    #                         - example-node #надо понять
                           
# ...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: local-path
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nextcloud-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: local-path
