kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisione
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: maria-pv
spec:
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce 
    persistentVolumeReclaimPolicy: Delete #Retain в будущем заменеить
    storageClassName: "local-storage"
    local:
        path: /mnt/flesh/mariadb #TODO Надо потом добавть
                    
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nextcloud-pv
spec:
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce 
    persistentVolumeReclaimPolicy: Delete #Retain в будущем заменеить
    storageClassName: "local-storage"
    local:
        path: /mnt/flesh/nextcloud #TODO Надо потом добавть                     
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 9Gi
    storageClassName: "local-storage"
    volumeName: maria-pv
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nextcloud-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 9Gi
    storageClassName: "local-storage"
    volumeName: nextcloud-pv
