apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home
spec:
  destination:
    name: ''
    namespace: 'home'
    server: 'https://kubernetes.default.svc'
  source:
    path: confs
    repoURL: 'git@github.com:atweek/home_server.git'
    targetRevision: dev
  sources: []
  project: default
