
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb 
  labels:
    app: mariadb 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb 
  template:
    metadata:
      labels:
        app: mariadb 
    spec:
      volumes:
      - name: mariadb-pvc
        persistentVolumeClaim:
          claimName: mariadb-pvc
      containers:
      - name: mariadb 
        image: mariadb:latest 
        ports:
          - containerPort: 3306
        env:
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                key: MYSQL_DATABASE
                name: apps-secrets
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: apps-secrets
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                key: MYSQL_USER
                name: apps-secrets
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: apps-secrets
        volumeMounts:
        - name: mariadb-pvc
          mountPath: /var/lib/mysql
