kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nextcloud-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: orange.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-service
            port:
              number: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:latest
        ports:
          - containerPort: 8080
--- 
kind: Service
apiVersion: v1
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
  - name: http
    port: 8080
    # targetPort: 8080