apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: 1000  # Ensure group permissions are correct for volumes
      volumes:
        - name: nextcloud-pvc
          persistentVolumeClaim:
            claimName: nextcloud-pvc
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/local/etc/php/conf.d"]
          volumeMounts:
            - mountPath: /usr/local/etc/php/conf.d
              name: nextcloud-pvc
      containers:
        - image: nextcloud:stable
          name: nextcloud
          ports:
            - containerPort: 80
          env:
            - name: PHP_MEMORY_LIMIT
              value: "5G"
            - name: PHP_UPLOAD_LIMIT
              value: "5G"
            - name: REDIS_HOST
              value: redis
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: apps-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: apps-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: apps-secrets
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN_PASS
                  name: apps-secrets
            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.atweek.work
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-pvc
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
