apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
      containers:
        - image: nextcloud:apache
          name: nextcloud
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
            - name: MYSQL_HOST
              value: mariadb 
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: apps-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: apps-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: apps-secrets
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: apps-secrets
            - name: NEXTCLOUD_ADMIN_USER
              value: "test"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                secretKeyRef:
                    key: NEXTCLOUD_TRUSTED_DOMAINS
                    name: apps-secrets
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-storage