kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app1-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: orange.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 80