----
#PersistentVolume hard drive
apiVersion: v1
kind: PersistentVolume
metadata:
    name: disk
spec:
    capacity:
        storage: 100Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: disk
    local:
        path: /mnt/disks/ssd1 #TODO Надо потом добавть
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - example-node #надо понять
                           
....
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: disk
....
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nextcloud-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 300Gi
    storageClassName: disk
